spy = eval(input("Enter the amount invested in SPY: "))
qqq = eval(input("Enter the amount invested in QQQ: "))
eem = eval(input("Enter the amount invested in EEM: "))
vxx = eval(input("Enter the amount invested in VXX: "))
print("{0:10s} {1:>10s}".format("ETF","PERCENTAGE"))
print('-'*22)
print("{0:10s} {1:>10,.2%}".format("SPY",spy/sum((spy,qqq,eem,vxx))))
print("{0:10s} {1:>10,.2%}".format("QQQ",qqq/sum((spy,qqq,eem,vxx))))
print("{0:10s} {1:>10,.2%}".format("EEM",eem/sum((spy,qqq,eem,vxx))))
print("{0:10s} {1:>10,.2%}".format("VXX",vxx/sum((spy,qqq,eem,vxx))))
print("\nTOTAL AMOUNT INVESTED: ${0:,.2f}".format(sum((spy,qqq,eem,vxx))))
